import numpy as np


def himmelblaus_function(input_vector) -> float:
    """
    a classic function used to test the performance of local search algorithms
    :param input_vector: vector of [x, y] values
    :return: function value at (x, y)
    """
    x, y = input_vector
    return (x**2 + y - 11)**2 + (x + y**2 - 7)**2


def ad_campaign_profit(input_vector):
    """
    A sample local-search problem.
    :param input_vector: vector of 4 numbers (each in range [0, 1]) representing amount to spend on 4 ad campaigns
    :return: revenue generated by the add campaigns
    """
    input_vector = np.array(input_vector) * 7 - 3
    x, y, z, _ = input_vector
    r = 60 - (np.sin(x + y) + (x - y)**2 - 1.5*x + 2.5*y + 1) + z/10
    return r
